services:
  vendor-portal:
    image: sudha0425/airlineselenium
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=vendorTest.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  fligh-reservation:
    image: sudha0425/airlineselenium
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output
